### ISSUE TITLE
Ambiguous fetch

### ISSUE THREAD

**Issue by sirioz** [StorageKit/StorageKit#21] opened 2017-08-28 15:04 UTC
I'd like to write:
```
context.fetch { (products: [Product]?) in 
   // things with my products
}

```
in order to fetch ALL my products.
But it doesn't compile. (It says: missing parameter)

**Comment by MarcoSantarossa** [comment] 2017-08-28 15:13
the problem is that `fetch` is an abstract method of a protocol:

```
func fetch<T>(predicate: NSPredicate?, sortDescriptors: [StorageKit.SortDescriptor]?, completion: @escaping ([T]?) -> Swift.Void) where T : StorageEntityType
```

and unfortunately Swift doesn't allow default parameters for the protocols. It means that we cannot omit `predicate` and `sortDescriptors` even if they are `nil`. A possible solution is to create a protocol extension where we implement `fetch` with default parameters to `nil`. Even if I'm not a big fan of this solution, I agree that it would clean the public interface. Another solution, maybe better than the previous one is adding another method to the protocol without parameters and just the completion closure. 

Thoughts?

cc @ennioma

**Comment by MarcoSantarossa** [comment] 2017-08-29 20:54
Issue fixed with https://github.com/StorageKit/StorageKit/pull/22. Thank you @sirioz for the contribution! ✌🏻

**Closed as completed by MarcoSantarossa** 2017-08-29 20:54 UTC
Labels: Enhancement, Merged
